server:
  port: 8008 #配置应用端口
spring:
  application:
    name: gateway-service #配置服务的名称
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 1.117.215.215:8848  #  注册中心地址
    gateway:
      enabled: true  #开启网关
      discovery:
        locator:
          enabled: true #开启自动路由,以服务id建立路由，服务id默认大写
          lower-case-service-id: true #服务id设置为小写
      routes:
      - id: rabbit-server
        uri: lb://rabbit-server
        predicates:
        - Path=/hystrix/** # 路径匹配
      - id: rabbit-product
        uri: lb://rabbit-product
        predicates:
        - Path=/hystrix1/** # 路径匹配
    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: 'http://localhost:9401/rsa/publicKey' #配置RSA的公钥访问地址