spring:
  rabbitmq:
    addresses: 1.117.215.215
    port: 15672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-confirm-type: correlated
    #开启ack
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual #采取手动应答